const express = require("express");
const cors = require("cors");
const transport = require("./transport.service");
const app = express(); app.use(cors()); app.use(express.json());
const ok = (res, data) => res.json({ success: true, data });
const fail = (res, status, code, message) => res.status(status).json({ success: false, error: { code, message } });
app.get("/health", (req, res) => ok(res, { service: "travelguard-data-provider", status: "healthy", simulation: transport.metadata() }));
app.get("/api/transports", (req, res) => ok(res, transport.search(req.query)));
app.get("/api/transports/search", (req, res) => ok(res, transport.search(req.query)));
app.get("/api/transports/history", (req, res) => ok(res, { dataset: "SYNTHETIC_REALTIME", records: transport.history(), simulation: transport.metadata() }));
app.get("/api/transports/:id/live", (req, res) => { const item = transport.byId(req.params.id); return item ? ok(res, item) : fail(res, 404, "TRANSPORT_NOT_FOUND", "Transport was not found"); });
app.get("/api/transports/:id/history", (req, res) => ok(res, transport.historyFor(req.params.id)));
app.get("/api/transports/:id", (req, res) => { const item = transport.byId(req.params.id); return item ? ok(res, item) : fail(res, 404, "TRANSPORT_NOT_FOUND", "Transport was not found"); });
app.get("/api/flights", (req, res) => ok(res, transport.search({ ...req.query, type: "FLIGHT" })));
app.get("/api/flights/:id", (req, res) => { const item = transport.byId(req.params.id); return item?.type === "FLIGHT" ? ok(res, item) : fail(res, 404, "FLIGHT_NOT_FOUND", "Flight was not found"); });
app.get("/api/trains", (req, res) => ok(res, transport.search({ ...req.query, type: "TRAIN" })));
app.get("/api/trains/:id", (req, res) => { const item = transport.byId(req.params.id); return item?.type === "TRAIN" ? ok(res, item) : fail(res, 404, "TRAIN_NOT_FOUND", "Train was not found"); });
app.post("/api/simulator/:transportId/delay", (req, res) => { const delay = Number(req.body?.delayMinutes); if (!Number.isInteger(delay) || delay < 0) return fail(res, 400, "INVALID_DELAY", "delayMinutes must be a non-negative integer"); const item = transport.applyDelay(req.params.transportId, delay); return item ? ok(res, item) : fail(res, 404, "TRANSPORT_NOT_FOUND", "Transport was not found"); });
app.post("/api/simulator/tick", (req, res) => ok(res, transport.tick()));
app.post("/api/simulator/reset", (req, res) => { transport.reset(); return ok(res, transport.metadata()); });
app.use((req, res) => fail(res, 404, "ROUTE_NOT_FOUND", "The requested route was not found"));
if (require.main === module) { const clock = transport.startClock(); const server = app.listen(Number(process.env.PORT || 5001), () => console.log("TravelGuard realtime provider running on port 5001")); process.on("SIGTERM", () => { clearInterval(clock); server.close(); }); }
module.exports = app;
